Release/1.0.1
snowplow-incubator/snowplow-micro-examples pull request #25
Opened 2021-08-25 08:12 UTC by adatzer

2021-08-25 10:07 UTC, mscwilson requested changes
Looks good. Very minor change(s) required, mainly the missing link.

2021-08-25 10:07 UTC, mscwilson commented on README.md
>  ## Table of Contents
nit/info: For Table of Contents links you only need the `#section` part! But this is fine too

2021-08-25 10:07 UTC, mscwilson commented on README.md
> +This is especially true when a tracking strategy is implemented, which means that any action can fire [events][snowplow-tracker-protocol] through the [trackers][snowplow-trackers]. There is an increa
Missing link re Gartner

2021-08-25 10:07 UTC, mscwilson commented on README.md
> + - [A Cypress issue describing a similar situation with XHR Aborts][cypress-xhr]
nit: Is this link still relevant? It could be good to add some more context.

2021-08-25 10:07 UTC, mscwilson commented on README.md
>   - Snowplow Micro now uses the exact same validation with a production Snowplow pipeline, which is even stricter and so ensures that if Micro validates an event, then it cannot fail during the enrich
nit: "as a production Snowplow pipeline" rather than "with a..."

2021-08-25 10:07 UTC, mscwilson commented on README.md
> +[gh-actions]: https://github.com/snowplow-incubator/snowplow-micro-examples/actions
I like this way of doing links!

2021-08-25 10:07 UTC, mscwilson commented on app/templates/ecommerce/index.html
> +        var opts = {
nit: `options` rather than `opts` might be more readable

2021-08-25 15:56 UTC, adatzer commented on README.md
>  ## Table of Contents
Thank you very much for reviewing @mscwilson !

I didn't know about the `#section` part! Changed!

2021-08-25 15:57 UTC, adatzer commented on README.md
> +This is especially true when a tracking strategy is implemented, which means that any action can fire [events][snowplow-tracker-protocol] through the [trackers][snowplow-trackers]. There is an increa
Good point.. maybe it's better to avoid the direct reference? I removed it and slightly rephrased. What do you think?

2021-08-25 16:01 UTC, mscwilson commented on README.md
> +This is especially true when a tracking strategy is implemented, which means that any action can fire [events][snowplow-tracker-protocol] through the [trackers][snowplow-trackers]. There is an increa
I think it's good now, don't really need the reference

2021-08-25 16:03 UTC, mscwilson approved these changes
lgtm 😊

2021-08-25 16:10 UTC, adatzer commented on README.md
> + - [A Cypress issue describing a similar situation with XHR Aborts][cypress-xhr]
You are absolutely right. First, it is indeed mentioned outside of context and second, it refers to a much older cypress version now. And indeed, after upgrading to v8, at least on local tests so far, i haven't seen this issue again. So, it made some sense to remove the link?

2021-08-25 16:15 UTC, mscwilson commented on README.md
> + - [A Cypress issue describing a similar situation with XHR Aborts][cypress-xhr]
i agree

2021-08-27 14:29 UTC, mscwilson approved these changes
lgtm

2021-08-27 16:43 UTC, merged